# Generated by Django 5.1.4 on 2024-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_logo_url_job_description_job_easy_apply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='easy_apply',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_highlighted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
